### ISSUE TITLE
Updating Person or Place doesn't update DC datastream

### ISSUE THREAD

**Issue by kayakr** [Islandora/islandora_solution_pack_entities#108]
Edting EAC-CPF or MADS for Person or Place updated EAC-CPF or MADS datastream revision but not DC datastream. Traced issue to use of islandora_entities_islandora_xml_form_builder_get_transforms() when it should be islandora_entities_xml_form_builder_get_transforms().

**Comment by DiegoPino** [comment]
@kayakr thanks for the pull. Please open a [JIRA](https://jira.duraspace.org/projects/ISLANDORA/issues) ticket for this issue. We are not managing issues in Github. Please ping me if you need help.

**Comment by kayakr** [comment]
@DiegoPino Thanks, have enquired about a JIRA account...

**Comment by DiegoPino** [comment]
@kayakr true. :open_mouth: Saw your CLA and thought you had one :sweat_smile: sorry! @manez could you please provide one for @kayakr? In the meantime i will make that Ticket for you.

**Comment by kayakr** [comment]
@DiegoPino Thanks.

**Comment by DiegoPino** [comment]
@kayakr JIRA opened
https://jira.duraspace.org/browse/ISLANDORA-1904. You can link to this from your commit message.
Also, some suggestions https://github.com/Islandora/islandora/wiki/Git-Guidelines-and-Best-Practices on naming your branches so JIRA and Github can speak the same language (mostly allowing JIRA to keep track of the associated pull). Thanks!

**Comment by dannylamb** [comment]
@DiegoPino If you don't mind, I'm going to close this issue and turn off issues altogether on this repo so we don't get another mixup.   

@kayakr Sorry for the confusion.  We use Github issues on CLAW but not on 7.x.
